/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cast.ui;

import cast.Cast;
import cast.models.Candidate;
import cast.models.Pageant;
import cast.tablemodels.CandidateTableModel;
import com.alee.extended.image.WebDecoratedImage;
import com.alee.global.GlobalConstants;
import com.alee.laf.filechooser.WebFileChooser;
import com.sun.glass.events.KeyEvent;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.RenderingHints; 
import java.awt.image.BufferedImage; 
import java.io.File; 
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List; 
import javax.imageio.ImageIO; 
import javax.swing.ImageIcon; 
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Zedlav
 */
public class CandidatePanel extends javax.swing.JPanel {
    private Pageant p;
    private int state = 1;
    private Candidate c;
    private CandidateTableModel cm;
    private WebDecoratedImage img = new WebDecoratedImage ();
    private BorderLayout bl;
    private WebFileChooser imageChooser = null;
    private File file = null;

    private static int ADD = 1;
    private static int EDIT = 2;
    private String path = Cast.getSystemDirectory()+"/photos/";
            
    /**
     * Creates new form CandidatePanel
     */
    public CandidatePanel()  throws SQLException{
        initComponents();
        
        p = Pageant.getPageant(1);
        this.bl = new BorderLayout();
        this.imgpanel.setLayout(bl);
        this.img.setShadeWidth ( 5 );
        this.img.setPreferredSize(new Dimension(160, 160));
        this.img.setDrawGlassLayer(false);
        this.imgpanel.add(img, BorderLayout.CENTER);
        
        display();
        reset();
    }

    public void display()throws SQLException{
        List<Candidate> l = p.getCandidates();
        cm = new CandidateTableModel(l);
        candidates.setModel(cm);
        candidates.setRowHeight(35);
        //resizeColumns();
    }
    
    public void display(List<Candidate> l)throws SQLException{
        cm = new CandidateTableModel(l);
        candidates.setModel(cm);
        candidates.setRowHeight(35);
        //resizeColumns();
    }
    public void resizeColumns(){
        TableColumnModel tcm = candidates.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(100);     //Name
        tcm.getColumn(1).setPreferredWidth(60);    //Title
        tcm.getColumn(2).setPreferredWidth(150);
        tcm.getColumn(3).setPreferredWidth(150);//Surname
        tcm.getColumn(4).setPreferredWidth(200);   
    }
    public void setPageant(Pageant pg){
        p = pg;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexGrp = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        candidates = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        candidateFname = new javax.swing.JTextField();
        candidateLname = new javax.swing.JTextField();
        candidateLabelNo = new javax.swing.JTextField();
        fbtn = new javax.swing.JRadioButton();
        mbtn = new javax.swing.JRadioButton();
        area = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        imgpanel = new javax.swing.JPanel();
        browse = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        candidates.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        candidates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                candidatesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(candidates);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 757, 320));

        jLabel1.setText("Candidate Name");

        jLabel2.setText("Candidate Label");

        jLabel3.setText("Candidate Sex");

        jLabel4.setText("Area Represented");

        candidateLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidateLnameActionPerformed(evt);
            }
        });

        sexGrp.add(fbtn);
        fbtn.setSelected(true);
        fbtn.setText("Female");

        sexGrp.add(mbtn);
        mbtn.setText("Male");
        mbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fbtn)
                                    .addGap(101, 101, 101))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(candidateFname)
                                    .addGap(10, 10, 10)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(candidateLname, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mbtn)))
                        .addComponent(area))
                    .addComponent(candidateLabelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(candidateFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candidateLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(candidateLabelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fbtn)
                    .addComponent(mbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 777, 10));

        add.setText("Save");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 67, -1));

        edit.setText("Update");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, -1, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 67, -1));

        cancel.setText("Clear");
        cancel.setFocusable(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 67, -1));

        jLabel5.setText("Search");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 20));

        q.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qKeyReleased(evt);
            }
        });
        add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 205, -1));

        imgpanel.setPreferredSize(new java.awt.Dimension(150, 170));

        javax.swing.GroupLayout imgpanelLayout = new javax.swing.GroupLayout(imgpanel);
        imgpanel.setLayout(imgpanelLayout);
        imgpanelLayout.setHorizontalGroup(
            imgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        imgpanelLayout.setVerticalGroup(
            imgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        add(imgpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 170, 180));

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        add(browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtnActionPerformed

    private void candidateLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidateLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidateLnameActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
        String fname = candidateFname.getText();
        String lname = candidateLname.getText();
        int cno = 0;
        try{
            cno = Integer.parseInt(candidateLabelNo.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please enter a valid candidate number!",
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
        }
        String gender = "";
        if (fbtn.isSelected()){
            gender = "Female";
        }else{
            gender = "Male";
        }
        String area = this.area.getText();
        String pic = "";
       
        if (fname.equals("") || lname.equals("") || cno == 0 || area.equals("")){
            JOptionPane.showMessageDialog(this, "Please enter required fields!", 
                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
        }else{
            
            if (state == ADD) {
                try{
                   
                    c = new Candidate();
                    c.setCandidateFname(fname);
                    c.setCandidateLname(lname);
                    c.setCandidateNoLabel(cno);
                    c.setGender(gender);
                    c.setArea(area);
                    
                    c.setPageantId(p.getPageantId());
                    if (file != null) {
                        int cid = Candidate.getLastID("candidateNo", "Candidate");
                        cid++;
                        pic = cid+".jpg";
                        c.setPhoto(pic);
                        int status = JOptionPane.showConfirmDialog(this, 
                                "Are you sure you want to add Candidate: "+c.getCandidateFname()+" "+c.getCandidateLname()+"?",
                                Cast.getSystemName(), JOptionPane.OK_CANCEL_OPTION);
                        if (status == JOptionPane.OK_OPTION) {
                            if (c.Add()){
                                try{
                                    BufferedImage image = ImageIO.read(file);
                                    BufferedImage scaled = Cast.getScaledInstance(
                                        image, 160, 160, RenderingHints.VALUE_INTERPOLATION_BILINEAR, true);
                                    Cast.writeJPG(scaled, new FileOutputStream(path+pic), 0.85f);
                                    JOptionPane.showMessageDialog(this, "You have successfully saved the information!",
                                        Cast.getSystemName(), JOptionPane.INFORMATION_MESSAGE);
                                    reset();
                                    display();
                                }catch(IOException e){
                                    JOptionPane.showMessageDialog(this, e.getMessage(),
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "An error occurred in saving the information!",
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                            }                       
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Please choose a photo of the Candidate!",
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage(),
                        Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                }
            }//end of ADD process
            else if (state == EDIT){
                try{
                    c.setCandidateFname(fname);
                    c.setCandidateLname(lname);
                    c.setCandidateNoLabel(cno);
                    c.setGender(gender);
                    c.setArea(area);
                    c.setPageantId(p.getPageantId());
                    
                    if (file != null) {
                        int status = JOptionPane.showConfirmDialog(this, 
                                "Are you sure you want to edit Candidate: "+c.getCandidateFname()+" "+c.getCandidateLname()+"?",
                                Cast.getSystemName(), JOptionPane.OK_CANCEL_OPTION);
                        if (status == JOptionPane.OK_OPTION) {
                            if (file == new File(path+c.getPhoto())) {
                                c.setPhoto(pic);
                            }else{
                                c.setPhoto(c.getCandidateNo()+".jpg");
                            }
                            if (c.Edit()){
                                if (file != new File(path+c.getPhoto())) {
                                    try{            
                                        BufferedImage image = ImageIO.read(file);
                                        BufferedImage scaled = Cast.getScaledInstance(
                                                image, 160, 160, RenderingHints.VALUE_INTERPOLATION_BILINEAR, true);
                                        Cast.writeJPG(scaled, new FileOutputStream(path+c.getPhoto()), 0.85f);
                                            JOptionPane.showMessageDialog(this, "You have successfully saved the information!",
                                                Cast.getSystemName(), JOptionPane.INFORMATION_MESSAGE);
                                        
                                        reset();
                                        display();
                                    }catch(IOException e){
                                            JOptionPane.showMessageDialog(this, e.getMessage(),
                                            Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            }else{
                                JOptionPane.showMessageDialog(this, "An error occurred in saving the information!",
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                            }                       
                        }
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage(),
                                Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        add.setEnabled(true);
        delete.setEnabled(false);
        edit.setEnabled(false);
        state = EDIT;
        isDisabled(true);
        browse.setEnabled(true);
    }//GEN-LAST:event_editActionPerformed
    
    public void reset(){
        state = ADD;
        c = null;
        file = null;
        this.candidateFname.setText("");
        this.candidateLname.setText("");
        this.area.setText("");
        this.mbtn.setSelected(false);
        this.fbtn.setSelected(true);
        this.candidateLabelNo.setText("");
        ImageIcon i = new ImageIcon(path+"default.jpg");
        this.img.setIcon(i, true);
        this.img.revalidate();
        this.img.repaint();
        
        edit.setEnabled(false);
        delete.setEnabled(false);
        add.setEnabled(true);
    }
    
    public void isDisabled(boolean t){
        this.candidateFname.setEnabled(t);
        this.candidateLname.setEnabled(t);
        this.area.setEnabled(t);
        this.mbtn.setEnabled(t);
        this.fbtn.setEnabled(t);
        this.candidateLabelNo.setEnabled(t);
    }
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        state = ADD;
        try{
            int status = JOptionPane.showConfirmDialog(this, 
                    "Are you sure you want to remove Candidate: "+c.getCandidateFname()+" "+c.getCandidateLname()+"?",
                    Cast.getSystemName(), JOptionPane.OK_CANCEL_OPTION);
            if (status == JOptionPane.OK_OPTION) {
                if (c.Delete()){
                    JOptionPane.showMessageDialog(this, 
                            "You have successfully removed the candidate from the pageant!",
                            Cast.getSystemName(), JOptionPane.INFORMATION_MESSAGE);
                    file.delete();
                    reset();
                    display();
                    isDisabled(true);
                    browse.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, 
                            "An error occurred in removing the candidate from the pageant!",
                            Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(),
                                Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void candidatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_candidatesMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2){
            isDisabled(false);
            try{
                browse.setEnabled(false);
                add.setEnabled(false);
                delete.setEnabled(true);
                edit.setEnabled(true);
                int row = candidates.getSelectedRow();
                cm = (CandidateTableModel) candidates.getModel();
                c = cm.getRowAt(row);
                candidateFname.setText(c.getCandidateFname());
                candidateLname.setText(c.getCandidateLname());
                candidateLabelNo.setText(c.getCandidateNoLabel()+"");
                if (c.getGender().equals("Female")){
                    fbtn.setSelected(true);
                }else{
                    mbtn.setSelected(true);
                }
                area.setText(c.getArea());
                
                file = new File(path+c.getPhoto());
                ImageIcon i = new ImageIcon(file.getAbsolutePath());
                img.setIcon(i, true);
                this.img.revalidate();
                this.img.repaint();
        
            }catch (NullPointerException e){
                ImageIcon i = new ImageIcon(path+"default.jpg");
                file = new File(path+"default.jpg");
                img.setIcon(i, true);
                this.img.revalidate();
                this.img.repaint();
        
            }catch(Exception e ){
                JOptionPane.showMessageDialog(this, e.getMessage(),
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_candidatesMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        reset();
        isDisabled(true);
        browse.setEnabled(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        // TODO add your handling code here:
        if ( imageChooser == null )
                {
                    imageChooser = new WebFileChooser ();
                    imageChooser.setMultiSelectionEnabled ( false );
                    imageChooser.setAcceptAllFileFilterUsed ( false );
                    imageChooser.addChoosableFileFilter ( GlobalConstants.IMAGES_FILTER );
                }
                if ( file != null )
                {
                    imageChooser.setSelectedFile ( file );
                    
                }
                if ( imageChooser.showOpenDialog ( this ) == WebFileChooser.APPROVE_OPTION )
                {
                    file = imageChooser.getSelectedFile ();
                    
                    Image i = new ImageIcon(file.getAbsolutePath()).getImage();
                    Image newimg = i.getScaledInstance(160, 160,  java.awt.Image.SCALE_SMOOTH);
                    img.setIcon(new ImageIcon(newimg));
                    this.img.revalidate();
                    this.img.repaint();
        
                }

    }//GEN-LAST:event_browseActionPerformed

    private void qKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            reset();
            String s = q.getText();
            if (s.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter a valid search query!",
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
            }else{
                try{
                    List<Candidate> cls = p.getCandidates(s);
                    if (cls.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "The search yielded no results! Displaying all participants!",
                                    Cast.getSystemName(), JOptionPane.INFORMATION_MESSAGE);
                        display();
                    }else{
                        display(cls);
                    }
                    
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(this, e.getMessage(),
                                    Cast.getSystemName(), JOptionPane.ERROR_MESSAGE);
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_qKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField area;
    private javax.swing.JButton browse;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField candidateFname;
    private javax.swing.JTextField candidateLabelNo;
    private javax.swing.JTextField candidateLname;
    private javax.swing.JTable candidates;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JRadioButton fbtn;
    private javax.swing.JPanel imgpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton mbtn;
    private javax.swing.JTextField q;
    private javax.swing.ButtonGroup sexGrp;
    // End of variables declaration//GEN-END:variables
}
